### ISSUE TITLE
Customize different types of carousels

### ISSUE THREAD

**Issue by rociocalvo** [mercadolibre/chico#1323]
It would be nice to make some modification to the carousel we already have on the Chico UI. 
We would like to have the availability to customize it, to be able to add our own properties, **example**: _Width, Height, Margin, Padding...etc._
Nowadays if we change properties, the limit per page does not work correctly. 

The idea is to create and customize different types of carousels like the attached example.

![captura de pantalla 2016-07-27 a las 1 21 21 a m](https://cloud.githubusercontent.com/assets/16102322/17164151/c940e5de-539b-11e6-92e2-b6337f8acf56.png)

**Comment by battaglr** [comment]
@rociocalvo, as per Chico [v2.0.6](https://github.com/mercadolibre/chico/releases/tag/v2.0.6) you have the ability to disable [`autoHeight`](http://chico.mercadolibre.com/api-doc/2.0.11/ui/ch.carousel/) and [`autoMargin`](http://chico.mercadolibre.com/api-doc/2.0.11/ui/ch.carousel/) which along with `limitPerPage` will allow you to customize the Carousel to a certain extent.

Options to allow further customizations will not be added since are not aligned with the project's current objectives.

Thank you very much for the suggestion. 😀
