### ISSUE TITLE
Centered columns

### ISSUE THREAD

**Issue by cRube** [mercadolibre/chico#1341]
Like this 

http://www.minimit.com/articles/solutions-tutorials/bootstrap-3-responsive-centered-columns

http://www.minimit.com/demos/bootstrap-3-responsive-centered-columns

**Comment by cRube** [comment]
Is there a way to center content (columns) using the currently Chico and Mesh codes? Thank you.

**Comment by battaglr** [comment]
@cRube, currently Mesh doesn't provide that feature —you could easily extend it for your use-case.

Keep in mind that Chico and [Mesh](https://github.com/mercadolibre/mesh/) are two separated projects. Honestly I don't see this feature being added to Mesh in the near future, since it relies entirely on floats. We might be able to accomplish something similar if https://github.com/mercadolibre/mesh/issues/15 gets implemented.

I'll be closing this, but feel free to [open an issue in Mesh](https://github.com/mercadolibre/mesh/issues) if you think that we should discuss this further.

Thanks!
