### ISSUE TITLE
Elemento sup en los precios  no es accesible

### ISSUE THREAD

**Issue by mrazzari** [mercadolibre/chico#632]
Es necesario un separador decimal. Sino el lector de pantalla lee a ambos como un solo número.

**Comment by atma** [comment]
There is already the price component as part of [typography](https://github.com/mercadolibre/chico/blob/v1.2.1/src/shared/styles/_typography.scss#L71-L96).

**Comment by mrazzari** [comment]
Where can I see an live HTML example of the "price component" in action?

**Comment by hmammana** [comment]
@atma I think you have to talk with Adolf because he started the changes of the price markup in MercadoPago & @HGARZON was with it too.

**Comment by battaglr** [comment]
We no longer "promote" the use of `ch-price` —for example, is not in the [documentation site](http://chico.mercadolibre.com/2x/ui/layout/).

Adding a "reviewed" version of this is not aligned with the project's current objectives, that's why I'm closing this.

That said, we are using an updated markup/style for prices in most parts of the site thanks to this suggestion, so thank you very much @mrazzari! Maybe we could consider sharing this on GitHub —CC/ @hmammana. If not, you can always inspect our code 😉
